language: python
os:
  - linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install nose2
  - pip install trimesh
  - python -c "import trimesh" #make sure base install works
  - pip install trimesh[easy]
script:
  - nose2